server:
  port: 8090

eureka:
  server:
    eureka.server.enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

spring:
  application:
    name: eurka-server